#       Copyright 2017-2020 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#Deploy the pod

---
apiVersion: v1
kind: List
items:
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: trader
    labels:
      app: stock-trader
  spec:
    template:
      metadata:
        labels:
          app: trader
      spec:
        containers:
        - name: trader
          image: 'ibmstocktrader/trader:latest'
          env:
            - name: WLP_LOGGING_CONSOLE_FORMAT
              value: json
            - name: WLP_LOGGING_CONSOLE_SOURCE
              value: message,ffdc
            - name: JWT_AUDIENCE
              value: trader
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: keycloak-oidc
                  key: OIDC_ISSUER
                  optional: true
            - name: OIDC_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: keycloak-oidc
                  key: OIDC_CLIENTID
                  optional: true
            - name: OIDC_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-oidc
                  key: OIDC_CLIENTSECRET
                  optional: true
            - name: OIDC_DISCOVERY_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-oidc
                  key: OIDC_DISCOVERY_URL
                  optional: true
            - name: PORTFOLIO_URL
              value: http://portfolio-service:9080/portfolio
            - name: AUTH_TYPE
              value: keycloak
          ports:
            - containerPort: 9080
            - containerPort: 9443
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
  #Deploy the service
  apiVersion: v1
  kind: Service
  metadata:
    name: trader-service
    labels:
      app: trader
      solution: stock-trader
  spec:
    ports:
      - name: http
        protocol: TCP
        port: 9080
        targetPort: 9080
      - name: https
        protocol: TCP
        port: 9443
        targetPort: 9443
    selector:
      app: trader
---
  # Openshift Route
  kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: trader
    labels:
      app: trader
      solution: stock-trader
  spec:
    to:
      kind: Service
      name: trader-service
      weight: 100
    port:
      targetPort: https
    tls:
      termination: passthrough
      insecureEdgeTerminationPolicy: None
    wildcardPolicy: None
